////////////////////////////////////////////////////////////////////////////////
//    ScopeFun Oscilloscope ( http://www.scopefun.com )
//    Copyright (C) 2016 - 2021 David Košenina
//    Copyright (C) 2021 - 2022 Dejan Priveršek
//
//    This file is part of ScopeFun Oscilloscope.
//
//    ScopeFun Oscilloscope is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    ScopeFun Oscilloscope is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this ScopeFun Oscilloscope.  If not, see <http://www.gnu.org/licenses/>.
//
////////////////////////////////////////////////////////////////////////////////
#ifndef __OsciloskopDebug__
#define __OsciloskopDebug__

/**
@file
Subclass of Debug, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

#include <scopefun/gui/OsciloskopOsciloskop.h>

/** Implementing Debug */
class OsciloskopDebug : public Debug
{
protected:
    // Handlers for Debug events.
    void ThermalOnActivate(wxActivateEvent& event);
	 void m_buttonStartOnButtonClick( wxCommandEvent& event );
	 void m_buttonStopOnButtonClick( wxCommandEvent& event );
	 void m_buttonSaveOnButtonClick( wxCommandEvent& event );
	 void m_buttonLuaOnButtonClick( wxCommandEvent& event );
	 void m_buttonHelpOnButtonClick( wxCommandEvent& event );
	 void m_buttonUploadOnButtonClick( wxCommandEvent& event );
public:
    /** Constructor */
    OsciloskopDebug(wxWindow* parent);
    ~OsciloskopDebug();
    //// end generated class members
private:
    void SetText(std::string str);
/* TODO: erase
private:
    OsciloscopeScript*           m_script;
*/
public:
    void OnDestroy(wxActivateEvent& event);
public:
    void ThreadStop();
    void Clear();
    void AppendText(const char* str);
public:
    void OnTimerUpdate(wxTimerEvent& event);
    wxTimer m_refreshTimer;
    /* TODO: erase
    void AssignScript(OsciloscopeScript* script) { m_script = script; }
    */

};

#endif // __OsciloskopDebug__
